message:
    pattern:  /
    defaults: { _controller: "FSBASTTAdminCrudBundle:Message:index" }

message_show:
    pattern:  /{id}/show
    defaults: { _controller: "FSBASTTAdminCrudBundle:Message:show" }

message_delete:
    pattern: /{id}/delete
    defaults: { _controller: "FSBASTTAdminCrudBundle:Message:delete" }
    requirements: { _method: post }