player:
    pattern:  /
    defaults: { _controller: "FSBASTTAdminCrudBundle:Player:index" }

player_show:
    pattern:  /{id}/show
    defaults: { _controller: "FSBASTTAdminCrudBundle:Player:show" }

player_new:
    pattern:  /new
    defaults: { _controller: "FSBASTTAdminCrudBundle:Player:new" }

player_create:
    pattern:  /create
    defaults: { _controller: "FSBASTTAdminCrudBundle:Player:create" }
    requirements: { _method: post }

player_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "FSBASTTAdminCrudBundle:Player:edit" }

player_update:
    pattern:  /{id}/update
    defaults: { _controller: "FSBASTTAdminCrudBundle:Player:update" }
    requirements: { _method: post }

player_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "FSBASTTAdminCrudBundle:Player:delete" }
    requirements: { _method: post }

player_import:
    pattern: /import
    defaults: { _controller: "FSBASTTAdminCrudBundle:Player:import" }

player_import_checkform:
    pattern: /import/check
    defaults: { _controller: "FSBASTTAdminCrudBundle:Player:importCheck" }
    requirements: { _method: post }