result:
    pattern:  /
    defaults: { _controller: "FSBASTTAdminCrudBundle:Result:index" }

result_show:
    pattern:  /{id}/show
    defaults: { _controller: "FSBASTTAdminCrudBundle:Result:show" }

result_new:
    pattern:  /new
    defaults: { _controller: "FSBASTTAdminCrudBundle:Result:new" }

result_create:
    pattern:  /create
    defaults: { _controller: "FSBASTTAdminCrudBundle:Result:create" }
    requirements: { _method: post }

result_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "FSBASTTAdminCrudBundle:Result:edit" }

result_update:
    pattern:  /{id}/update
    defaults: { _controller: "FSBASTTAdminCrudBundle:Result:update" }
    requirements: { _method: post }

result_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "FSBASTTAdminCrudBundle:Result:delete" }
    requirements: { _method: post }
