FSBASTTFrontBundle:
    resource: "@FSBASTTFrontBundle/Resources/config/routing.yml"
    prefix:   /

FSBASTTAdminCrudBundle:
    resource: "@FSBASTTAdminCrudBundle/Resources/config/routing.yml"
    prefix:   /admin/