FSBASTTFrontBundle:
    resource: "@FSBASTTFrontBundle/Resources/config/routing.yml"
    prefix:   /

FSBASTTAdminCrudBundle:
    resource: "@FSBASTTAdminCrudBundle/Resources/config/routing.yml"
    prefix:   /admin/

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
