security:
    #encoders:
        #Symfony\Component\Security\Core\User\User: plaintext

    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm:   sha1
            iterations: 1
            encode_as_base64: false
            
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        astt:
            users:
                arnaud: { password: 4a64bdd9da55875b0c673bc2bd2ebd6733934b0c, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        
        admin_login:
            pattern: ^/admin/login$
            anonymous: ~
        
        admin_area:
            pattern: ^/admin
            form_login:
                login_path: /admin/login
                check_path: /admin/login_check
                default_target_path: /admin/news
                post_only: true
            logout:
                path: /admin/logout
                target: /admin/login
            
    access_control:
        - { path: ^/admin/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }