parameters:
#    fsbastt_front.example.class: FSB\ASTT\FrontBundle\Example

services:
#    fsbastt_front.example:
#        class: %fsbastt_front.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
